name: CICD

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        run: |
          scp -o StrictHostKeyChecking=no -i "~/.ssh/id_rsa" run.sh ec2-user@ec2-3-87-41-161.compute-1.amazonaws.com:~/
          ssh -o StrictHostKeyChecking=no -i "~/.ssh/id_rsa" ec2-user@ec2-3-87-41-161.compute-1.amazonaws.com "sudo chmod +x run.sh && sudo ./run.sh"
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SERVER_CONFIG: ${{secrets.SERVER_CONFIG}}
      START_UP: ${{vars.START_UP}}